### ISSUE TITLE
Activation error

### ISSUE THREAD

**Issue by feedhopper** [hartenthaler/german-wars-battles-worldwide#2]
This looks great. however, when I try activating the plugin, I get this:

```
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x87\xA9\xF0\x9F...' for column `d03be594`.`wt_session`.`session_data` at row 1 (SQL: update `wt_session` set `session_data` = initiated|b:1;_GUEST_sessiontime|s:10:"1674736188";language|s:2:"de";theme|s:20:"_jc-theme-justlight_";CSRF_TOKEN|s:32:"JQZdTAX4RGxMvGvRvN2uYczW1KfVA0Cl";captcha-t|d:1674736196.5323469638824462890625;captcha-x|s:32:"8a29ce7b163946309c84d2143e64874e";captcha-y|s:32:"2893fbe006114632a3dfaf62e5fc4ce5";captcha-z|s:32:"7f5d8549e54a47f89137c7cc84c92e47";wt_user|i:1;flash_messages|a:1:{i:0;O:8:"stdClass":2:{s:4:"text";s:68:"Das Modul “Wars and Battles Worldwide 🇩🇪” wurde aktiviert.";s:6:"status";s:7:"success";}} where `session_id` = 3b5458048bb7d349ebe6df71c46d0a96) …/vendor/illuminate/database/Connection.php:712
#0 …/vendor/illuminate/database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback('update `wt_sess...', Array, Object(Closure))
#1 …/vendor/illuminate/database/Connection.php(533): Illuminate\Database\Connection->run('update `wt_sess...', Array, Object(Closure))
#2 …/vendor/illuminate/database/Connection.php(466): Illuminate\Database\Connection->affectingStatement('update `wt_sess...', Array)
#3 …/vendor/illuminate/database/Query/Builder.php(3063): Illuminate\Database\Connection->update('update `wt_sess...', Array)
#4 …/app/SessionDatabaseHandler.php(125): Illuminate\Database\Query\Builder->update(Array)
#5 [internal function]: Fisharebest\Webtrees\SessionDatabaseHandler->write('3b5458048bb7d34...', 'initiated|b:1;_...')
#6 …/app/Session.php(100): session_write_close()
#7 …/app/Http/Middleware/UseSession.php(80): Fisharebest\Webtrees\Session::save()
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#9 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#11 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#13 …/app/Http/Middleware/BadBotBlocker.php(282): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#15 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#16 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#17 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#19 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#20 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#21 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#22 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#24 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#26 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#28 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#29 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#30 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#33 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#34 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
#35 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#36 {main}
```

What is the problem?

**Comment by hartenthaler** [comment]
I don't know. Maybe:

There is a message "Das Modul “Wars and Battles Worldwide 🇩🇪” wurde aktiviert." including the special character "🇩🇪". There are several similar modules with other such country codes. What happens if you try to activate such another historic data module? Does the same error appear? Or is it related only to my module? Which database in which version are you using?
